---
kind: pipeline
name: "Push on master"

steps:
- name: node
  image: node
  commands:
  - npm install
  - npm run build

- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: registry_username
    password:
      from_secret: registry_password
    repo: astronautns/supabase-nextjs
    tags: ${DRONE_COMMIT_SHA:0:7}

trigger:
  branch:
    exclude:
    - master